version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data/projects:/app/projects
      - ./data/indexes:/app/indexes
      - ./data/logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - ANALYZER_PARSER_THREAD_COUNT=4
      - ANALYZER_CACHE_ENABLE=true
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped